name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.system.os }}
    strategy:
      fail-fast: false
      matrix:
        system:
          - os: windows-2016
            mono: ""
            triplet: x86-windows
          - os: windows-2019
            mono: ""
            triplet: x64-windows

        build-type: ["Debug", "Release"]

    env:
      VCPKG_FEATURE_FLAGS: binarycaching,manifests
      VCPKG_BINARY_SOURCES: clear;nuget,GitHub,readwrite

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Bootstrap vcpkg (Windows)
        if: runner.os == 'Windows'
        run: ./vcpkg/bootstrap-vcpkg.bat
      - name: Bootstrap vcpkg (Unix-like)
        if: runner.os != 'Windows'
        run: ./vcpkg/bootstrap-vcpkg.sh

      - name: Prepare vcpkg
        shell: bash
        run: >
          ${{ matrix.system.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/Hoikas/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "Hoikas"
          -password "${{ secrets.GITHUB_TOKEN }}"

      - name: Build
        shell: bash
        run: |
          mkdir build && cd build
          cmake --version
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/build/install" \
            -DVCPKG_TARGET_TRIPLET=${{ matrix.system.triplet }} \
            -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON \
            ..
          cmake --build .

      - name: Install (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake --build build --target INSTALL --config ${{ matrix.build-type }}
      - name: Install (Unix)
        if: runner.os != 'Windows'
        run: |
          cmake --build build --target install

      - name: Upload Installed Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: INSTALL ${{ runner.os }} ${{ matrix.system.triplet }} ${{ matrix.build-type }}
          path: ${{ github.workspace }}/build/install

      - name: Upload Failure Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: LOG ${{ runner.os }} ${{ matrix.system.triplet }} ${{ matrix.build-type }}
          path: ${{ github.workspace }}/**/*.log

      - name: Upload CMakeCache
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: CMakeCache ${{ runner.os }} ${{ matrix.system.triplet }} ${{ matrix.build-type }}
          path: ${{ github.workspace }}/**/CMakeCache.txt

      - name: List Directory Contents
        if: always()
        run: ls -R build
