name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        #cmake-defines: ["-DOLD_FINDERS=ON", "-DNEW_FINDERS=ON", "-DNEW_FINDERS=ON -DOLD_FINDERS=ON", "-DOLD_FINDERS=ON -DOLD_FINDERS_WRONG_ORDER=ON"]
        #build-type: ["Debug", "Release"]

    env:
      VCPKG_FEATURE_FLAGS: binarycaching,manifests
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/deps,readwrite

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/deps
          key: |
            ${{ runner.os }} ${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DVCPKG_MANIFEST_MODE=ON ${{ matrix.cmake-defines }} ..

      - name: Upload Failure Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: LOG ${{ runner.os }} ${{ matrix.build-type }} ${{ matrix.cmake-defines }}
          path: ${{ github.workspace }}/**/*.log

      - name: List Build Directory
        if: always()
        run: ls -R build
